### PR TITLE
feat(Tabs): introduce new component and preset

### LINKED ISSUE #144: feat(Tabs): new component and preset
### 🆒 Your use case

I can take it on myself.

Снимок экрана 2024-07-25 в 22 33 17

### 🆕 The solution you'd like

So, I think I'll make some components which will contain: 
- wrapper
- triggers
- content (I'll  think on this about it in more detail)

### 🔍 Alternatives you've considered

_No response_

### ℹ️ Additional info

In making this. We will use https://www.radix-vue.com/components/tabs.html for instant unstyled component.

Consider this as a guide when making this component: https://github.com/radix-vue/shadcn-vue/tree/dev/apps/www/src/lib/registry/default/ui/tabs ✨ 

Here's an example to what I did to [Slider](https://unaui.com/components/slider#component) using https://radix-vue.com/

### 🏗️  Todos

- [x] Add component (ref: https://unaui.com/components/slider#component)
- [x] Add presets (ref: https://unaui.com/components/slider#presets)
- [x] Add props (ref: https://unaui.com/components/slider#props)
- [x] Add docs
- [x] Add examples

### PR DESCRIPTION
**Pull request by mnenie**
resolves #144 

### Description

@phojie hello 👋

So, I made Tabs. But I have some problems/shortcomings which I could have improved but couldn't
1. I made separate components and did not make an index.vue in runtime because I can't understand how in this case, even if it is implemented through slots. I think its can keep the individual components and the user will set them according to the structure
2. I made it possible to change the color via `tabs={color}` but I tried to make smth like Button or Badge (with solid, link variants) in directory slots in runtime (for nesting colors) but I'm facing a reactivity problem because of (I guess) the render function. So I kept segments with styling in packages/preset/src/_shortcuts/tabs.ts

So, I need your review. Thanks !!!

Снимок экрана 2024-08-03 в 22 15 48

### CODE REVIEW

**Comment by mnenie** [comment]
> Hello @mnenie,
> 
> In the meantime, you might want to take a look at this newly added component: [Select Component](https://unaui.com/components/select).
> 
> It includes subcomponents along with the main component, similar to the architecture we might want here.
> 
> Instead of using slots to define items why not do something like this
> 
> ` <NTabs :items="items" />`

thanks @phojie !

in the process of developing this now

**Comment by mnenie** [comment]
@phojie 

So I fixed and now we have 
```html 
<NTabs :items="items" default-value="tab1" />
```

check please the last commit 
thanks !

**Comment by phojie** [comment]
> @phojie
> 
> So I fixed and now we have
> 
> ```
> <NTabs :items="items" default-value="tab1" />
> ```
> 
> check please the last commit thanks !

@mnenie  damn, so fassstt. nice work 🚀 , will review this soooon 🎸

**Comment by phojie** [comment]
Close as merge in https://github.com/una-ui/una-ui/pull/152

**Pull request closed without merging**
