### PR TITLE
fix(types): Generate nuxt types automatically at install

### PR DESCRIPTION
**Pull request by killjoy1221**
This removes the need for `/* @ts-expect-error */` and generally improves the DX.

I'm not sure if this is generally the recommended way to do this for modules, but it seems to work.

### CODE REVIEW

**Comment by killjoy1221** [comment]
Typescript seems to be picking up the playground components declared in .nuxt/components.d.ts and trying to typecheck them. Oh well.

**Comment by mnenie** [comment]
> Typescript seems to be picking up the playground components declared in .nuxt/components.d.ts and trying to typecheck them. Oh well.

yea, I worked with the same problem in nuxt.com when fixing the bugs for our docs. but maybe `@nuxt/types` in `types` is the solution

**Comment by phojie** [comment]
@killjoy1221  did you resolves this one already?

**Comment by phojie** [comment]
this might be lint configuration problem only

**Review by phojie — APPROVED** [review]

**Comment by phojie** [comment]
Thanks @killjoy1221 , this is all working now 🚀

**Comment by mnenie** [comment]
yea thanks @killjoy1221 💯

**Pull request merged**
