### PR TITLE
refactor(popover): Simpler interface for NPopover

### PR DESCRIPTION
**Pull request by killjoy1221**
I've made simpler interface for Popover, which is also more similar to nuxt/ui.

Breaking changes and migration:

- Replace radix-vue's required `PopoverTrigger` with the `default` slot.
- Replace usage of `NPopoverContent` with the `popper` slot.
- Props for `<NPopoverContent>` can be passed via the `<NPopover :popper="{}">`

Old code:
```vue
<NPopover>
  <NPopoverTrigger as-child>
    <NButton>Click me</NButton>
  </NPopoverTrigger>
  <NPopoverContent align="start" class="w-80">
    Popover content
  </NPopoverContent>
</NPopover>
```

New, simpler code:
```vue
<NPopover :_popover-content="{align: 'start', class: 'w-80'}">
  <NButton>Click me</NButton>
  <template #content>
    Popover content
  </template>
</NPopover>
```

### CODE REVIEW

**Comment by phojie** [comment]
Hello @killjoy1221, I understand that Una-UI currently doesn't have a clear anatomy or architecture yet. but here's my insight on this:

## Props

In the [Nuxt UI Popover component](https://ui.nuxt.com/components/popover) from the current version, they are using `HeadlessUI` for their unstyled components, which we are no longer using in our upcoming components including this one. Since we are now using [Radix Vue's Popover](https://www.radix-vue.com/components/popover.html#anatomy) for this, we're aiming to maintain its anatomy as much as possible. This approach will make Una-UI more future-proof for upcoming updates in Radix (e.g., additions or changes in props and emits), by simply passing all the current props through subcomponents (e.g., `_popoverContent`). This way, it will be easier for us to refer to Radix docs for additional API information.

Note that the `NuxtUI` team is also migrating from HeadlessUI to RadixUI. In fact, Una-UI is the closest to following the same direction. You can check their `Popover` repo here: https://github.com/nuxt/ui/blob/v3/src/runtime/components/Popover.vue#L22.

## Slots

But you have a good point here, in having `slot` instead of using `PopoverContent`, this is really good idea. same what we have in https://unaui.com/components/tooltip#slots.

❌  old code

```.vue
<NPopover>
  <NPopoverTrigger as-child>
    <NButton>Click me</NButton>
  </NPopoverTrigger>
  <NPopoverContent align="start" class="w-80">
    Popover content
  </NPopoverContent>
</NPopover>
```

✅ new code

```.vue
<NPopover
	:_popover-content={
	    side: 'top',
	}
>
      <NButton>Click me</NButton>
      
	  <template #content>
	      Popover content
	  </template>
</NPopover>
```

for `_popover-content` props, it can pass what ever available props in https://www.radix-vue.com/components/popover.html#content 

---

What do you think, @killjoy1221 @mnenie ? Feel free to add your suggestions here 💛 . You're really doing a good job. We are being enlightened to improve this `Popover`."

Let me know if you'd like any further changes! 🚀

**Comment by mnenie** [comment]
> Hello @killjoy1221, I understand that Una-UI currently doesn't have a clear anatomy or architecture yet. but here's my insight on this:
> 
> ## Props
> In the [Nuxt UI Popover component](https://ui.nuxt.com/components/popover) from the current version, they are using `HeadlessUI` for their unstyled components, which we are no longer using in our upcoming components including this one. Since we are now using [Radix Vue's Popover](https://www.radix-vue.com/components/popover.html#anatomy) for this, we're aiming to maintain its anatomy as much as possible. This approach will make Una-UI more future-proof for upcoming updates in Radix (e.g., additions or changes in props and emits), by simply passing all the current props through subcomponents (e.g., `_popoverContent`). This way, it will be easier for us to refer to Radix docs for additional API information.
> 
> Note that the `NuxtUI` team is also migrating from HeadlessUI to RadixUI. In fact, Una-UI is the closest to following the same direction. You can check their `Popover` repo here: https://github.com/nuxt/ui/blob/v3/src/runtime/components/Popover.vue#L22.
> 
> ## Slots
> But you have a good point here, in having `slot` instead of using `PopoverContent`, this is really good idea. same what we have in https://unaui.com/components/tooltip#slots.
> 
> ❌ old code
> 
> ```
> <NPopover>
>   <NPopoverTrigger as-child>
>     <NButton>Click me</NButton>
>   </NPopoverTrigger>
>   <NPopoverContent align="start" class="w-80">
>     Popover content
>   </NPopoverContent>
> </NPopover>
> ```
> 
> ✅ new code
> 
> ```
> <NPopover
> 	:_popover-content={
> 	    side: 'top',
> 	}
> >
>       <NButton>Click me</NButton>
>       
> 	  <template #content>
> 	      Popover content
> 	  </template>
> </NPopover>
> ```
> 
> for `_popover-content` props, it can pass what ever available props in https://www.radix-vue.com/components/popover.html#content
> 
> What do you think, @killjoy1221 @mnenie ? Feel free to add your suggestions here 💛 . You're really doing a good job. We are being enlightened to improve this `Popover`.
> 
> Let me know if you'd like any further changes! 🚀

@phojie looks good

**Comment by killjoy1221** [comment]
@phojie Sounds like a good idea. I'll work on making the changes.

**Comment by killjoy1221** [comment]
All set!

**Comment by phojie** [comment]
Thanks for this @killjoy1221 , do you want to join us in discord ? please drop your id here 💛

**Comment by killjoy1221** [comment]
@phojie I'm 171783421377511425

**Comment by phojie** [comment]
@killjoy1221 , looks like I cant see your account, but heres the invitation link. 

https://discord.gg/CjRKzEzD

come join with us! 💛

**Pull request merged**
